name: build

on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]*'
      - 'v[0-9]*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: win32
            display-name: Windows 32-bit
            runs-on: windows-2019
            release-arch: Win32
            os-type: Windows
            build-type: Release
          - name: win64
            display-name: Windows 64-bit
            runs-on: windows-2019
            release-arch: x64
            os-type: Windows
            build-type: Release
          - name: linux64
            display-name: Linux 64-bit
            runs-on: ubuntu-20.04
            os-type: Linux
            build-type: Release
          - name: macos
            display-name: macOS
            runs-on: macos-11  
            os-type: macOS
            build-type: Release
      fail-fast: false
    name: Compile for ${{ matrix.display-name }}
    runs-on: ${{ matrix.runs-on }}
    env:
      name: ${{ matrix.name }}
      display_name: ${{ matrix.display-name }}
      release_arch: ${{ matrix.release-arch }}
      build_type: ${{ matrix.build-type }}
      num_jobs: 2
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Create Build Directory
        working-directory: ${{ runner.workspace }}
        run: cmake -E make_directory build
      - name: Configure CMake (Windows)
        if: ${{ matrix.os-type == 'Windows' }}
        working-directory: ${{ runner.workspace }}/build
        run: cmake "${Env:GITHUB_WORKSPACE}" -G"Visual Studio 16 2019" -A"${Env:release_arch}" -DCMAKE_BUILD_TYPE="${Env:build_type}" -DCMAKE_CXX_STANDARD=17
      - name: Configure CMake (Linux)
        if: ${{ matrix.os-type == 'Linux' }}
        working-directory: ${{ runner.workspace }}/build
        run: cmake "${GITHUB_WORKSPACE}" -DCMAKE_BUILD_TYPE="${build_type}" -DCMAKE_CXX_STANDARD=17
      - name: Configure CMake (macOS)
        if: ${{ matrix.os-type == 'macOS' }}
        working-directory: ${{ runner.workspace }}/build
        run: cmake "${GITHUB_WORKSPACE}" -DCMAKE_BUILD_TYPE="${build_type}" -DCMAKE_CXX_STANDARD=17 -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
      - name: Build (Windows)
        if: ${{ matrix.os-type == 'Windows' }}
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build . --config "${Env:build_type}" -j "${Env:num_jobs}"
      - name: Build (Linux/macOS)
        if: ${{ matrix.os-type == 'Linux' || matrix.os-type == 'macOS' }}
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build . --config "${build_type}" -j "${num_jobs}"
      - uses: apple-actions/import-codesign-certs@v1
        if: ${{ matrix.os-type == 'macOS' && github.event_name != 'pull_request' }}
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      - name: Sign
        if: ${{ matrix.os-type == 'macOS' && github.event_name != 'pull_request' }}
        working-directory: ${{runner.workspace}}/build
        run: |
          codesign --sign "${CODESIGN_IDENTITY}" --keychain signing_temp.keychain --deep --force --verbose bin/*.vst
      - uses: actions/upload-artifact@v2
        with:
          name: Fverb for ${{ matrix.display-name }}
          path: "${{runner.workspace}}/build/bin/*"
